/*
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.0.1
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.recruitment.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.recruitment.pojos.Agreeableness;
import br.com.senior.hcm.recruitment.pojos.Conscientiousness;
import br.com.senior.hcm.recruitment.pojos.Extraversion;
import br.com.senior.hcm.recruitment.pojos.Neuroticism;
import br.com.senior.hcm.recruitment.pojos.Openness;
import br.com.senior.hcm.recruitment.pojos.PersonalityModelCandidate;
import java.io.IOException;

/**
 * BigFive
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-10T16:52:01.386Z")



public class BigFive {
  @SerializedName("conscientiousness")
  private Conscientiousness conscientiousness = null;

  @SerializedName("personalityModelCandidate")
  private PersonalityModelCandidate personalityModelCandidate = null;

  @SerializedName("openness")
  private Openness openness = null;

  @SerializedName("neuroticism")
  private Neuroticism neuroticism = null;

  @SerializedName("extraversion")
  private Extraversion extraversion = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("agreeableness")
  private Agreeableness agreeableness = null;

  public BigFive conscientiousness(Conscientiousness conscientiousness) {
    this.conscientiousness = conscientiousness;
    return this;
  }

   /**
   * Get conscientiousness
   * @return conscientiousness
  **/
  @ApiModelProperty(value = "")
  public Conscientiousness getConscientiousness() {
    return conscientiousness;
  }

  public void setConscientiousness(Conscientiousness conscientiousness) {
    this.conscientiousness = conscientiousness;
  }

  public BigFive personalityModelCandidate(PersonalityModelCandidate personalityModelCandidate) {
    this.personalityModelCandidate = personalityModelCandidate;
    return this;
  }

   /**
   * Get personalityModelCandidate
   * @return personalityModelCandidate
  **/
  @ApiModelProperty(value = "")
  public PersonalityModelCandidate getPersonalityModelCandidate() {
    return personalityModelCandidate;
  }

  public void setPersonalityModelCandidate(PersonalityModelCandidate personalityModelCandidate) {
    this.personalityModelCandidate = personalityModelCandidate;
  }

  public BigFive openness(Openness openness) {
    this.openness = openness;
    return this;
  }

   /**
   * Get openness
   * @return openness
  **/
  @ApiModelProperty(value = "")
  public Openness getOpenness() {
    return openness;
  }

  public void setOpenness(Openness openness) {
    this.openness = openness;
  }

  public BigFive neuroticism(Neuroticism neuroticism) {
    this.neuroticism = neuroticism;
    return this;
  }

   /**
   * Get neuroticism
   * @return neuroticism
  **/
  @ApiModelProperty(value = "")
  public Neuroticism getNeuroticism() {
    return neuroticism;
  }

  public void setNeuroticism(Neuroticism neuroticism) {
    this.neuroticism = neuroticism;
  }

  public BigFive extraversion(Extraversion extraversion) {
    this.extraversion = extraversion;
    return this;
  }

   /**
   * Get extraversion
   * @return extraversion
  **/
  @ApiModelProperty(value = "")
  public Extraversion getExtraversion() {
    return extraversion;
  }

  public void setExtraversion(Extraversion extraversion) {
    this.extraversion = extraversion;
  }

  public BigFive id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BigFive agreeableness(Agreeableness agreeableness) {
    this.agreeableness = agreeableness;
    return this;
  }

   /**
   * Get agreeableness
   * @return agreeableness
  **/
  @ApiModelProperty(value = "")
  public Agreeableness getAgreeableness() {
    return agreeableness;
  }

  public void setAgreeableness(Agreeableness agreeableness) {
    this.agreeableness = agreeableness;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BigFive bigFive = (BigFive) o;
    return Objects.equals(this.conscientiousness, bigFive.conscientiousness) &&
        Objects.equals(this.personalityModelCandidate, bigFive.personalityModelCandidate) &&
        Objects.equals(this.openness, bigFive.openness) &&
        Objects.equals(this.neuroticism, bigFive.neuroticism) &&
        Objects.equals(this.extraversion, bigFive.extraversion) &&
        Objects.equals(this.id, bigFive.id) &&
        Objects.equals(this.agreeableness, bigFive.agreeableness);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conscientiousness, personalityModelCandidate, openness, neuroticism, extraversion, id, agreeableness);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BigFive {\n");
    
    sb.append("    conscientiousness: ").append(toIndentedString(conscientiousness)).append("\n");
    sb.append("    personalityModelCandidate: ").append(toIndentedString(personalityModelCandidate)).append("\n");
    sb.append("    openness: ").append(toIndentedString(openness)).append("\n");
    sb.append("    neuroticism: ").append(toIndentedString(neuroticism)).append("\n");
    sb.append("    extraversion: ").append(toIndentedString(extraversion)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    agreeableness: ").append(toIndentedString(agreeableness)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

