/*
 * Recrutamento e Seleção
 * Serviço do Gestão de Recrutamento e Seleção.
 *
 * OpenAPI spec version: 16.1.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.recruitment.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.recruitment.pojos.ModelStageTypeDto;
import br.com.senior.hcm.recruitment.pojos.RecruitmentProcessStage;
import java.io.IOException;

/**
 * ModelStage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-20T21:23:01.692Z")



public class ModelStage {
  @SerializedName("sequence")
  private Integer sequence = null;

  @SerializedName("medicalExam")
  private Boolean medicalExam = null;

  @SerializedName("recruitmentProcessStage")
  private RecruitmentProcessStage recruitmentProcessStage = null;

  @SerializedName("modelId")
  private String modelId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("type")
  private ModelStageTypeDto type = null;

  public ModelStage sequence(Integer sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Sequência da etapa
   * @return sequence
  **/
  @ApiModelProperty(value = "Sequência da etapa")
  public Integer getSequence() {
    return sequence;
  }

  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }

  public ModelStage medicalExam(Boolean medicalExam) {
    this.medicalExam = medicalExam;
    return this;
  }

   /**
   * Indica se a etapa é de exame médico.
   * @return medicalExam
  **/
  @ApiModelProperty(value = "Indica se a etapa é de exame médico.")
  public Boolean isMedicalExam() {
    return medicalExam;
  }

  public void setMedicalExam(Boolean medicalExam) {
    this.medicalExam = medicalExam;
  }

  public ModelStage recruitmentProcessStage(RecruitmentProcessStage recruitmentProcessStage) {
    this.recruitmentProcessStage = recruitmentProcessStage;
    return this;
  }

   /**
   * Get recruitmentProcessStage
   * @return recruitmentProcessStage
  **/
  @ApiModelProperty(value = "")
  public RecruitmentProcessStage getRecruitmentProcessStage() {
    return recruitmentProcessStage;
  }

  public void setRecruitmentProcessStage(RecruitmentProcessStage recruitmentProcessStage) {
    this.recruitmentProcessStage = recruitmentProcessStage;
  }

  public ModelStage modelId(String modelId) {
    this.modelId = modelId;
    return this;
  }

   /**
   * Identificador único do modelo a qual está etapa pertence.
   * @return modelId
  **/
  @ApiModelProperty(value = "Identificador único do modelo a qual está etapa pertence.")
  public String getModelId() {
    return modelId;
  }

  public void setModelId(String modelId) {
    this.modelId = modelId;
  }

  public ModelStage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nome da etapa.
   * @return name
  **/
  @ApiModelProperty(value = "Nome da etapa.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ModelStage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identificador único da entidade.
   * @return id
  **/
  @ApiModelProperty(value = "Identificador único da entidade.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ModelStage type(ModelStageTypeDto type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public ModelStageTypeDto getType() {
    return type;
  }

  public void setType(ModelStageTypeDto type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelStage modelStage = (ModelStage) o;
    return Objects.equals(this.sequence, modelStage.sequence) &&
        Objects.equals(this.medicalExam, modelStage.medicalExam) &&
        Objects.equals(this.recruitmentProcessStage, modelStage.recruitmentProcessStage) &&
        Objects.equals(this.modelId, modelStage.modelId) &&
        Objects.equals(this.name, modelStage.name) &&
        Objects.equals(this.id, modelStage.id) &&
        Objects.equals(this.type, modelStage.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequence, medicalExam, recruitmentProcessStage, modelId, name, id, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelStage {\n");
    
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    medicalExam: ").append(toIndentedString(medicalExam)).append("\n");
    sb.append("    recruitmentProcessStage: ").append(toIndentedString(recruitmentProcessStage)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

