/*
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.sam.application.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CctvProxy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-24T13:38:01.755Z")



public class CctvProxy {
  @SerializedName("port")
  private Integer port = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("host")
  private String host = null;

  @SerializedName("id")
  private Integer id = null;

  public CctvProxy port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Porta de Comunicação
   * @return port
  **/
  @ApiModelProperty(value = "Porta de Comunicação")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public CctvProxy name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nome do Proxy CFTV
   * @return name
  **/
  @ApiModelProperty(value = "Nome do Proxy CFTV")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CctvProxy host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Host
   * @return host
  **/
  @ApiModelProperty(value = "Host")
  public String getHost() {
    return host;
  }

  public void setHost(String host) {
    this.host = host;
  }

  public CctvProxy id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(value = "ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CctvProxy cctvProxy = (CctvProxy) o;
    return Objects.equals(this.port, cctvProxy.port) &&
        Objects.equals(this.name, cctvProxy.name) &&
        Objects.equals(this.host, cctvProxy.host) &&
        Objects.equals(this.id, cctvProxy.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(port, name, host, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CctvProxy {\n");
    
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

