/*
 * Aplicação
 * Serviço do backend da aplicação do Ronda senior X
 *
 * OpenAPI spec version: 4.7.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.sam.application.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.sam.application.pojos.AccessCall;
import br.com.senior.sam.application.pojos.MovementDirection;
import br.com.senior.sam.application.pojos.Person;
import br.com.senior.sam.application.pojos.Role;
import br.com.senior.sam.application.pojos.VirtualLobby;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * VirtualLobbyMovement
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-24T13:38:01.755Z")



public class VirtualLobbyMovement {
  @SerializedName("virtualLobby")
  private VirtualLobby virtualLobby = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  @SerializedName("role")
  private Role role = null;

  @SerializedName("movementDirection")
  private MovementDirection movementDirection = null;

  @SerializedName("accessCall")
  private AccessCall accessCall = null;

  @SerializedName("responsible")
  private Person responsible = null;

  @SerializedName("visited")
  private Person visited = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("visitor")
  private Person visitor = null;

  public VirtualLobbyMovement virtualLobby(VirtualLobby virtualLobby) {
    this.virtualLobby = virtualLobby;
    return this;
  }

   /**
   * Get virtualLobby
   * @return virtualLobby
  **/
  @ApiModelProperty(value = "")
  public VirtualLobby getVirtualLobby() {
    return virtualLobby;
  }

  public void setVirtualLobby(VirtualLobby virtualLobby) {
    this.virtualLobby = virtualLobby;
  }

  public VirtualLobbyMovement createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Data de criação
   * @return createdAt
  **/
  @ApiModelProperty(value = "Data de criação")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public VirtualLobbyMovement role(Role role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public Role getRole() {
    return role;
  }

  public void setRole(Role role) {
    this.role = role;
  }

  public VirtualLobbyMovement movementDirection(MovementDirection movementDirection) {
    this.movementDirection = movementDirection;
    return this;
  }

   /**
   * Get movementDirection
   * @return movementDirection
  **/
  @ApiModelProperty(value = "")
  public MovementDirection getMovementDirection() {
    return movementDirection;
  }

  public void setMovementDirection(MovementDirection movementDirection) {
    this.movementDirection = movementDirection;
  }

  public VirtualLobbyMovement accessCall(AccessCall accessCall) {
    this.accessCall = accessCall;
    return this;
  }

   /**
   * Get accessCall
   * @return accessCall
  **/
  @ApiModelProperty(value = "")
  public AccessCall getAccessCall() {
    return accessCall;
  }

  public void setAccessCall(AccessCall accessCall) {
    this.accessCall = accessCall;
  }

  public VirtualLobbyMovement responsible(Person responsible) {
    this.responsible = responsible;
    return this;
  }

   /**
   * Get responsible
   * @return responsible
  **/
  @ApiModelProperty(value = "")
  public Person getResponsible() {
    return responsible;
  }

  public void setResponsible(Person responsible) {
    this.responsible = responsible;
  }

  public VirtualLobbyMovement visited(Person visited) {
    this.visited = visited;
    return this;
  }

   /**
   * Get visited
   * @return visited
  **/
  @ApiModelProperty(value = "")
  public Person getVisited() {
    return visited;
  }

  public void setVisited(Person visited) {
    this.visited = visited;
  }

  public VirtualLobbyMovement id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * ID
   * @return id
  **/
  @ApiModelProperty(value = "ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public VirtualLobbyMovement visitor(Person visitor) {
    this.visitor = visitor;
    return this;
  }

   /**
   * Get visitor
   * @return visitor
  **/
  @ApiModelProperty(value = "")
  public Person getVisitor() {
    return visitor;
  }

  public void setVisitor(Person visitor) {
    this.visitor = visitor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualLobbyMovement virtualLobbyMovement = (VirtualLobbyMovement) o;
    return Objects.equals(this.virtualLobby, virtualLobbyMovement.virtualLobby) &&
        Objects.equals(this.createdAt, virtualLobbyMovement.createdAt) &&
        Objects.equals(this.role, virtualLobbyMovement.role) &&
        Objects.equals(this.movementDirection, virtualLobbyMovement.movementDirection) &&
        Objects.equals(this.accessCall, virtualLobbyMovement.accessCall) &&
        Objects.equals(this.responsible, virtualLobbyMovement.responsible) &&
        Objects.equals(this.visited, virtualLobbyMovement.visited) &&
        Objects.equals(this.id, virtualLobbyMovement.id) &&
        Objects.equals(this.visitor, virtualLobbyMovement.visitor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtualLobby, createdAt, role, movementDirection, accessCall, responsible, visited, id, visitor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualLobbyMovement {\n");
    
    sb.append("    virtualLobby: ").append(toIndentedString(virtualLobby)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    movementDirection: ").append(toIndentedString(movementDirection)).append("\n");
    sb.append("    accessCall: ").append(toIndentedString(accessCall)).append("\n");
    sb.append("    responsible: ").append(toIndentedString(responsible)).append("\n");
    sb.append("    visited: ").append(toIndentedString(visited)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    visitor: ").append(toIndentedString(visitor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

