/*
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.4.2
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.dependent.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets employeeType
 */
@JsonAdapter(EmployeeType.Adapter.class)
public enum EmployeeType {
  
  NULL("NULL"),
  
  EMPLOYEE("EMPLOYEE"),
  
  THIRD("THIRD"),
  
  PARTNER("PARTNER");

  private String value;

  EmployeeType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EmployeeType fromValue(String text) {
    for (EmployeeType b : EmployeeType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EmployeeType> {
    @Override
    public void write(final JsonWriter jsonWriter, final EmployeeType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EmployeeType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EmployeeType.fromValue(String.valueOf(value));
    }
  }
}

