/*
 * Dependentes
 * HCM - Gestão de dependentes
 *
 * OpenAPI spec version: 6.0.0
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.dependent.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets genderType
 */
@JsonAdapter(GenderType.Adapter.class)
public enum GenderType {
  
  MALE("Male"),
  
  FEMALE("Female");

  private String value;

  GenderType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GenderType fromValue(String text) {
    for (GenderType b : GenderType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<GenderType> {
    @Override
    public void write(final JsonWriter jsonWriter, final GenderType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GenderType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GenderType.fromValue(String.valueOf(value));
    }
  }
}

