/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.Apportionment;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Department
 */




public class Department {
  @SerializedName("nightTimeHoliday")
  private String nightTimeHoliday = null;

  @SerializedName("creationdate")
  private LocalDate creationdate = null;

  @SerializedName("code")
  private String code = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("daytimeHoliday")
  private String daytimeHoliday = null;

  @SerializedName("apportionment")
  private Apportionment apportionment = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("position")
  private String position = null;

  @SerializedName("tablecode")
  private Integer tablecode = null;

  @SerializedName("expirationdate")
  private LocalDate expirationdate = null;

  public Department nightTimeHoliday(String nightTimeHoliday) {
    this.nightTimeHoliday = nightTimeHoliday;
    return this;
  }

   /**
   * Id da tabela de feriados noturnos
   * @return nightTimeHoliday
  **/
  @ApiModelProperty(value = "Id da tabela de feriados noturnos")
  public String getNightTimeHoliday() {
    return nightTimeHoliday;
  }

  public void setNightTimeHoliday(String nightTimeHoliday) {
    this.nightTimeHoliday = nightTimeHoliday;
  }

  public Department creationdate(LocalDate creationdate) {
    this.creationdate = creationdate;
    return this;
  }

   /**
   * Data de criação
   * @return creationdate
  **/
  @ApiModelProperty(required = true, value = "Data de criação")
  public LocalDate getCreationdate() {
    return creationdate;
  }

  public void setCreationdate(LocalDate creationdate) {
    this.creationdate = creationdate;
  }

  public Department code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Código do local
   * @return code
  **/
  @ApiModelProperty(required = true, value = "Código do local")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Department name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Nome do local
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Nome do local")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Department daytimeHoliday(String daytimeHoliday) {
    this.daytimeHoliday = daytimeHoliday;
    return this;
  }

   /**
   * Id da tabela de feriados diurnos
   * @return daytimeHoliday
  **/
  @ApiModelProperty(value = "Id da tabela de feriados diurnos")
  public String getDaytimeHoliday() {
    return daytimeHoliday;
  }

  public void setDaytimeHoliday(String daytimeHoliday) {
    this.daytimeHoliday = daytimeHoliday;
  }

  public Department apportionment(Apportionment apportionment) {
    this.apportionment = apportionment;
    return this;
  }

   /**
   * Get apportionment
   * @return apportionment
  **/
  @ApiModelProperty(value = "")
  public Apportionment getApportionment() {
    return apportionment;
  }

  public void setApportionment(Apportionment apportionment) {
    this.apportionment = apportionment;
  }

  public Department externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Id de sistema externo
   * @return externalId
  **/
  @ApiModelProperty(value = "Id de sistema externo")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public Department id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id do local
   * @return id
  **/
  @ApiModelProperty(value = "Id do local")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Department position(String position) {
    this.position = position;
    return this;
  }

   /**
   * Posição
   * @return position
  **/
  @ApiModelProperty(required = true, value = "Posição")
  public String getPosition() {
    return position;
  }

  public void setPosition(String position) {
    this.position = position;
  }

  public Department tablecode(Integer tablecode) {
    this.tablecode = tablecode;
    return this;
  }

   /**
   * Código da tabela
   * @return tablecode
  **/
  @ApiModelProperty(required = true, value = "Código da tabela")
  public Integer getTablecode() {
    return tablecode;
  }

  public void setTablecode(Integer tablecode) {
    this.tablecode = tablecode;
  }

  public Department expirationdate(LocalDate expirationdate) {
    this.expirationdate = expirationdate;
    return this;
  }

   /**
   * Data de extinção
   * @return expirationdate
  **/
  @ApiModelProperty(required = true, value = "Data de extinção")
  public LocalDate getExpirationdate() {
    return expirationdate;
  }

  public void setExpirationdate(LocalDate expirationdate) {
    this.expirationdate = expirationdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Department department = (Department) o;
    return Objects.equals(this.nightTimeHoliday, department.nightTimeHoliday) &&
        Objects.equals(this.creationdate, department.creationdate) &&
        Objects.equals(this.code, department.code) &&
        Objects.equals(this.name, department.name) &&
        Objects.equals(this.daytimeHoliday, department.daytimeHoliday) &&
        Objects.equals(this.apportionment, department.apportionment) &&
        Objects.equals(this.externalId, department.externalId) &&
        Objects.equals(this.id, department.id) &&
        Objects.equals(this.position, department.position) &&
        Objects.equals(this.tablecode, department.tablecode) &&
        Objects.equals(this.expirationdate, department.expirationdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nightTimeHoliday, creationdate, code, name, daytimeHoliday, apportionment, externalId, id, position, tablecode, expirationdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Department {\n");
    
    sb.append("    nightTimeHoliday: ").append(toIndentedString(nightTimeHoliday)).append("\n");
    sb.append("    creationdate: ").append(toIndentedString(creationdate)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    daytimeHoliday: ").append(toIndentedString(daytimeHoliday)).append("\n");
    sb.append("    apportionment: ").append(toIndentedString(apportionment)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    tablecode: ").append(toIndentedString(tablecode)).append("\n");
    sb.append("    expirationdate: ").append(toIndentedString(expirationdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

