/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.EmailType;
import java.io.IOException;

/**
 * Email
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-14T17:15:20.586Z")



public class Email {
  @SerializedName("person")
  private String person = null;

  @SerializedName("emailtype")
  private EmailType emailtype = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("email")
  private String email = null;

  public Email person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Relacionamento com pessoa
   * @return person
  **/
  @ApiModelProperty(value = "Relacionamento com pessoa")
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public Email emailtype(EmailType emailtype) {
    this.emailtype = emailtype;
    return this;
  }

   /**
   * Get emailtype
   * @return emailtype
  **/
  @ApiModelProperty(value = "")
  public EmailType getEmailtype() {
    return emailtype;
  }

  public void setEmailtype(EmailType emailtype) {
    this.emailtype = emailtype;
  }

  public Email id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id do email
   * @return id
  **/
  @ApiModelProperty(value = "Id do email")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Email email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Endereço de email
   * @return email
  **/
  @ApiModelProperty(value = "Endereço de email")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Email email = (Email) o;
    return Objects.equals(this.person, email.person) &&
        Objects.equals(this.emailtype, email.emailtype) &&
        Objects.equals(this.id, email.id) &&
        Objects.equals(this.email, email.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, emailtype, id, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Email {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    emailtype: ").append(toIndentedString(emailtype)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

