/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.Attachment;
import br.com.senior.hcm.payroll.pojos.Company;
import br.com.senior.hcm.payroll.pojos.ContractNationalityType;
import br.com.senior.hcm.payroll.pojos.EmployeeContractType;
import br.com.senior.hcm.payroll.pojos.EmployeeType;
import br.com.senior.hcm.payroll.pojos.HireType;
import br.com.senior.hcm.payroll.pojos.Jobposition;
import br.com.senior.hcm.payroll.pojos.Person;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Employee
 */




public class Employee {
  @SerializedName("employeetype")
  private EmployeeType employeetype = null;

  @SerializedName("workshift")
  private String workshift = null;

  @SerializedName("hireType")
  private HireType hireType = null;

  @SerializedName("companynumber")
  private Integer companynumber = null;

  @SerializedName("processNumber")
  private String processNumber = null;

  @SerializedName("jobposition")
  private Jobposition jobposition = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("hiredate")
  private LocalDate hiredate = null;

  @SerializedName("registrationnumber")
  private Integer registrationnumber = null;

  @SerializedName("isOccupyQuotaDisability")
  private Boolean isOccupyQuotaDisability = null;

  @SerializedName("contracttype")
  private EmployeeContractType contracttype = null;

  @SerializedName("appearsinRais")
  private Boolean appearsinRais = null;

  @SerializedName("attachment")
  private Attachment attachment = null;

  @SerializedName("person")
  private Person person = null;

  @SerializedName("employer")
  private Company employer = null;

  @SerializedName("dismissaldate")
  private LocalDate dismissaldate = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("department")
  private String department = null;

  @SerializedName("contractNationality")
  private ContractNationalityType contractNationality = null;

  @SerializedName("costcenter")
  private String costcenter = null;

  @SerializedName("registernumber")
  private Integer registernumber = null;

  public Employee employeetype(EmployeeType employeetype) {
    this.employeetype = employeetype;
    return this;
  }

   /**
   * Get employeetype
   * @return employeetype
  **/
  @ApiModelProperty(required = true, value = "")
  public EmployeeType getEmployeetype() {
    return employeetype;
  }

  public void setEmployeetype(EmployeeType employeetype) {
    this.employeetype = employeetype;
  }

  public Employee workshift(String workshift) {
    this.workshift = workshift;
    return this;
  }

   /**
   * Relacionamento com posto de trabalho
   * @return workshift
  **/
  @ApiModelProperty(value = "Relacionamento com posto de trabalho")
  public String getWorkshift() {
    return workshift;
  }

  public void setWorkshift(String workshift) {
    this.workshift = workshift;
  }

  public Employee hireType(HireType hireType) {
    this.hireType = hireType;
    return this;
  }

   /**
   * Get hireType
   * @return hireType
  **/
  @ApiModelProperty(required = true, value = "")
  public HireType getHireType() {
    return hireType;
  }

  public void setHireType(HireType hireType) {
    this.hireType = hireType;
  }

  public Employee companynumber(Integer companynumber) {
    this.companynumber = companynumber;
    return this;
  }

   /**
   * Empresa do colaborador: NUMEMP
   * @return companynumber
  **/
  @ApiModelProperty(required = true, value = "Empresa do colaborador: NUMEMP")
  public Integer getCompanynumber() {
    return companynumber;
  }

  public void setCompanynumber(Integer companynumber) {
    this.companynumber = companynumber;
  }

  public Employee processNumber(String processNumber) {
    this.processNumber = processNumber;
    return this;
  }

   /**
   * Processo judicial
   * @return processNumber
  **/
  @ApiModelProperty(value = "Processo judicial")
  public String getProcessNumber() {
    return processNumber;
  }

  public void setProcessNumber(String processNumber) {
    this.processNumber = processNumber;
  }

  public Employee jobposition(Jobposition jobposition) {
    this.jobposition = jobposition;
    return this;
  }

   /**
   * Get jobposition
   * @return jobposition
  **/
  @ApiModelProperty(required = true, value = "")
  public Jobposition getJobposition() {
    return jobposition;
  }

  public void setJobposition(Jobposition jobposition) {
    this.jobposition = jobposition;
  }

  public Employee externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Id externo
   * @return externalId
  **/
  @ApiModelProperty(value = "Id externo")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public Employee hiredate(LocalDate hiredate) {
    this.hiredate = hiredate;
    return this;
  }

   /**
   * Data de admissão
   * @return hiredate
  **/
  @ApiModelProperty(required = true, value = "Data de admissão")
  public LocalDate getHiredate() {
    return hiredate;
  }

  public void setHiredate(LocalDate hiredate) {
    this.hiredate = hiredate;
  }

  public Employee registrationnumber(Integer registrationnumber) {
    this.registrationnumber = registrationnumber;
    return this;
  }

   /**
   * Número de registro do colaborador
   * @return registrationnumber
  **/
  @ApiModelProperty(required = true, value = "Número de registro do colaborador")
  public Integer getRegistrationnumber() {
    return registrationnumber;
  }

  public void setRegistrationnumber(Integer registrationnumber) {
    this.registrationnumber = registrationnumber;
  }

  public Employee isOccupyQuotaDisability(Boolean isOccupyQuotaDisability) {
    this.isOccupyQuotaDisability = isOccupyQuotaDisability;
    return this;
  }

   /**
   * Ocupa cota de deficiente?
   * @return isOccupyQuotaDisability
  **/
  @ApiModelProperty(required = true, value = "Ocupa cota de deficiente?")
  public Boolean isIsOccupyQuotaDisability() {
    return isOccupyQuotaDisability;
  }

  public void setIsOccupyQuotaDisability(Boolean isOccupyQuotaDisability) {
    this.isOccupyQuotaDisability = isOccupyQuotaDisability;
  }

  public Employee contracttype(EmployeeContractType contracttype) {
    this.contracttype = contracttype;
    return this;
  }

   /**
   * Get contracttype
   * @return contracttype
  **/
  @ApiModelProperty(required = true, value = "")
  public EmployeeContractType getContracttype() {
    return contracttype;
  }

  public void setContracttype(EmployeeContractType contracttype) {
    this.contracttype = contracttype;
  }

  public Employee appearsinRais(Boolean appearsinRais) {
    this.appearsinRais = appearsinRais;
    return this;
  }

   /**
   * Consta na RAIS?
   * @return appearsinRais
  **/
  @ApiModelProperty(required = true, value = "Consta na RAIS?")
  public Boolean isAppearsinRais() {
    return appearsinRais;
  }

  public void setAppearsinRais(Boolean appearsinRais) {
    this.appearsinRais = appearsinRais;
  }

  public Employee attachment(Attachment attachment) {
    this.attachment = attachment;
    return this;
  }

   /**
   * Get attachment
   * @return attachment
  **/
  @ApiModelProperty(value = "")
  public Attachment getAttachment() {
    return attachment;
  }

  public void setAttachment(Attachment attachment) {
    this.attachment = attachment;
  }

  public Employee person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @ApiModelProperty(required = true, value = "")
  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public Employee employer(Company employer) {
    this.employer = employer;
    return this;
  }

   /**
   * Get employer
   * @return employer
  **/
  @ApiModelProperty(required = true, value = "")
  public Company getEmployer() {
    return employer;
  }

  public void setEmployer(Company employer) {
    this.employer = employer;
  }

  public Employee dismissaldate(LocalDate dismissaldate) {
    this.dismissaldate = dismissaldate;
    return this;
  }

   /**
   * Data de demissão
   * @return dismissaldate
  **/
  @ApiModelProperty(value = "Data de demissão")
  public LocalDate getDismissaldate() {
    return dismissaldate;
  }

  public void setDismissaldate(LocalDate dismissaldate) {
    this.dismissaldate = dismissaldate;
  }

  public Employee id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id do colaborador
   * @return id
  **/
  @ApiModelProperty(value = "Id do colaborador")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Employee department(String department) {
    this.department = department;
    return this;
  }

   /**
   * Relacionamento com o local
   * @return department
  **/
  @ApiModelProperty(required = true, value = "Relacionamento com o local")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public Employee contractNationality(ContractNationalityType contractNationality) {
    this.contractNationality = contractNationality;
    return this;
  }

   /**
   * Get contractNationality
   * @return contractNationality
  **/
  @ApiModelProperty(required = true, value = "")
  public ContractNationalityType getContractNationality() {
    return contractNationality;
  }

  public void setContractNationality(ContractNationalityType contractNationality) {
    this.contractNationality = contractNationality;
  }

  public Employee costcenter(String costcenter) {
    this.costcenter = costcenter;
    return this;
  }

   /**
   * Centro de custo
   * @return costcenter
  **/
  @ApiModelProperty(value = "Centro de custo")
  public String getCostcenter() {
    return costcenter;
  }

  public void setCostcenter(String costcenter) {
    this.costcenter = costcenter;
  }

  public Employee registernumber(Integer registernumber) {
    this.registernumber = registernumber;
    return this;
  }

   /**
   * Código do colaborador: NUMCAD
   * @return registernumber
  **/
  @ApiModelProperty(required = true, value = "Código do colaborador: NUMCAD")
  public Integer getRegisternumber() {
    return registernumber;
  }

  public void setRegisternumber(Integer registernumber) {
    this.registernumber = registernumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Employee employee = (Employee) o;
    return Objects.equals(this.employeetype, employee.employeetype) &&
        Objects.equals(this.workshift, employee.workshift) &&
        Objects.equals(this.hireType, employee.hireType) &&
        Objects.equals(this.companynumber, employee.companynumber) &&
        Objects.equals(this.processNumber, employee.processNumber) &&
        Objects.equals(this.jobposition, employee.jobposition) &&
        Objects.equals(this.externalId, employee.externalId) &&
        Objects.equals(this.hiredate, employee.hiredate) &&
        Objects.equals(this.registrationnumber, employee.registrationnumber) &&
        Objects.equals(this.isOccupyQuotaDisability, employee.isOccupyQuotaDisability) &&
        Objects.equals(this.contracttype, employee.contracttype) &&
        Objects.equals(this.appearsinRais, employee.appearsinRais) &&
        Objects.equals(this.attachment, employee.attachment) &&
        Objects.equals(this.person, employee.person) &&
        Objects.equals(this.employer, employee.employer) &&
        Objects.equals(this.dismissaldate, employee.dismissaldate) &&
        Objects.equals(this.id, employee.id) &&
        Objects.equals(this.department, employee.department) &&
        Objects.equals(this.contractNationality, employee.contractNationality) &&
        Objects.equals(this.costcenter, employee.costcenter) &&
        Objects.equals(this.registernumber, employee.registernumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeetype, workshift, hireType, companynumber, processNumber, jobposition, externalId, hiredate, registrationnumber, isOccupyQuotaDisability, contracttype, appearsinRais, attachment, person, employer, dismissaldate, id, department, contractNationality, costcenter, registernumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Employee {\n");
    
    sb.append("    employeetype: ").append(toIndentedString(employeetype)).append("\n");
    sb.append("    workshift: ").append(toIndentedString(workshift)).append("\n");
    sb.append("    hireType: ").append(toIndentedString(hireType)).append("\n");
    sb.append("    companynumber: ").append(toIndentedString(companynumber)).append("\n");
    sb.append("    processNumber: ").append(toIndentedString(processNumber)).append("\n");
    sb.append("    jobposition: ").append(toIndentedString(jobposition)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    hiredate: ").append(toIndentedString(hiredate)).append("\n");
    sb.append("    registrationnumber: ").append(toIndentedString(registrationnumber)).append("\n");
    sb.append("    isOccupyQuotaDisability: ").append(toIndentedString(isOccupyQuotaDisability)).append("\n");
    sb.append("    contracttype: ").append(toIndentedString(contracttype)).append("\n");
    sb.append("    appearsinRais: ").append(toIndentedString(appearsinRais)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    employer: ").append(toIndentedString(employer)).append("\n");
    sb.append("    dismissaldate: ").append(toIndentedString(dismissaldate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    contractNationality: ").append(toIndentedString(contractNationality)).append("\n");
    sb.append("    costcenter: ").append(toIndentedString(costcenter)).append("\n");
    sb.append("    registernumber: ").append(toIndentedString(registernumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

