/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets eSocialCategory
 */
@JsonAdapter(ESocialCategory.Adapter.class)
public enum ESocialCategory {
  
  _101("Category_101"),
  
  _102("Category_102"),
  
  _103("Category_103"),
  
  _104("Category_104"),
  
  _105("Category_105"),
  
  _106("Category_106"),
  
  _111("Category_111"),
  
  _201("Category_201"),
  
  _202("Category_202"),
  
  _301("Category_301"),
  
  _302("Category_302"),
  
  _303("Category_303"),
  
  _305("Category_305"),
  
  _306("Category_306"),
  
  _307("Category_307"),
  
  _308("Category_308"),
  
  _309("Category_309"),
  
  _401("Category_401"),
  
  _410("Category_410"),
  
  _701("Category_701"),
  
  _711("Category_711"),
  
  _712("Category_712"),
  
  _721("Category_721"),
  
  _722("Category_722"),
  
  _723("Category_723"),
  
  _731("Category_731"),
  
  _734("Category_734"),
  
  _738("Category_738"),
  
  _741("Category_741"),
  
  _751("Category_751"),
  
  _761("Category_761"),
  
  _771("Category_771"),
  
  _781("Category_781"),
  
  _901("Category_901"),
  
  _902("Category_902"),
  
  _903("Category_903"),
  
  _904("Category_904"),
  
  _905("Category_905"),
  
  _997("Category_997"),
  
  _998("Category_998"),
  
  _999("Category_999");

  private String value;

  ESocialCategory(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ESocialCategory fromValue(String text) {
    for (ESocialCategory b : ESocialCategory.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ESocialCategory> {
    @Override
    public void write(final JsonWriter jsonWriter, final ESocialCategory enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ESocialCategory read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ESocialCategory.fromValue(String.valueOf(value));
    }
  }
}

