/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.ESocialCategory;
import br.com.senior.hcm.payroll.pojos.Employee;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * HistoricalEsocialCategory
 */

public class HistoricalEsocialCategory {
  @SerializedName("dateWhen")
  private LocalDate dateWhen = null;

  @SerializedName("endDate")
  private LocalDate endDate = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("employee")
  private Employee employee = null;

  @SerializedName("eSocialCategoryType")
  private ESocialCategory eSocialCategoryType = null;

  public HistoricalEsocialCategory dateWhen(LocalDate dateWhen) {
    this.dateWhen = dateWhen;
    return this;
  }

   /**
   * Data do histórico
   * @return dateWhen
  **/
  @ApiModelProperty(required = true, value = "Data do histórico")
  public LocalDate getDateWhen() {
    return dateWhen;
  }

  public void setDateWhen(LocalDate dateWhen) {
    this.dateWhen = dateWhen;
  }

  public HistoricalEsocialCategory endDate(LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Data de término
   * @return endDate
  **/
  @ApiModelProperty(value = "Data de término")
  public LocalDate getEndDate() {
    return endDate;
  }

  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }

  public HistoricalEsocialCategory id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id do histórico
   * @return id
  **/
  @ApiModelProperty(value = "Id do histórico")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public HistoricalEsocialCategory employee(Employee employee) {
    this.employee = employee;
    return this;
  }

   /**
   * Get employee
   * @return employee
  **/
  @ApiModelProperty(required = true, value = "")
  public Employee getEmployee() {
    return employee;
  }

  public void setEmployee(Employee employee) {
    this.employee = employee;
  }

  public HistoricalEsocialCategory eSocialCategoryType(ESocialCategory eSocialCategoryType) {
    this.eSocialCategoryType = eSocialCategoryType;
    return this;
  }

   /**
   * Get eSocialCategoryType
   * @return eSocialCategoryType
  **/
  @ApiModelProperty(required = true, value = "")
  public ESocialCategory getESocialCategoryType() {
    return eSocialCategoryType;
  }

  public void setESocialCategoryType(ESocialCategory eSocialCategoryType) {
    this.eSocialCategoryType = eSocialCategoryType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoricalEsocialCategory historicalEsocialCategory = (HistoricalEsocialCategory) o;
    return Objects.equals(this.dateWhen, historicalEsocialCategory.dateWhen) &&
        Objects.equals(this.endDate, historicalEsocialCategory.endDate) &&
        Objects.equals(this.id, historicalEsocialCategory.id) &&
        Objects.equals(this.employee, historicalEsocialCategory.employee) &&
        Objects.equals(this.eSocialCategoryType, historicalEsocialCategory.eSocialCategoryType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateWhen, endDate, id, employee, eSocialCategoryType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoricalEsocialCategory {\n");
    
    sb.append("    dateWhen: ").append(toIndentedString(dateWhen)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    employee: ").append(toIndentedString(employee)).append("\n");
    sb.append("    eSocialCategoryType: ").append(toIndentedString(eSocialCategoryType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

