/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets kinshipDegree
 */
@JsonAdapter(KinshipDegree.Adapter.class)
public enum KinshipDegree {
  
  ADOPTED("Adopted"),
  
  CHILD("Child"),
  
  CONCUBINE("Concubine"),
  
  EXSPOUSE("ExSpouse"),
  
  EXPARTNER("ExPartner"),
  
  GRANDPARENT("Grandparent"),
  
  GRANDCHILD("Grandchild"),
  
  GREATGRANDPARENT("GreatGrandparent"),
  
  GREATGRANDCHILD("GreatGrandchild"),
  
  GUARDIANSHIP("Guardianship"),
  
  NEPHEWNIECE("NephewNiece"),
  
  OTHER("Other"),
  
  PARENT("Parent"),
  
  FATHERINLAW("FatherInLaw"),
  
  PARTNER("Partner"),
  
  PENSIONERS("Pensioners"),
  
  PUPIL("Pupil"),
  
  SIBLING("Sibling"),
  
  SONDAUGHTERINLAW("SonDaughterInLaw"),
  
  SPOUSE("Spouse"),
  
  STEPFATHER("Stepfather"),
  
  STEPMOTHER("Stepmother"),
  
  STEPCHILD("Stepchild"),
  
  TRUSTED("Trusted"),
  
  UNCLEAUNT("UncleAunt"),
  
  TUTOR("Tutor");

  private String value;

  KinshipDegree(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static KinshipDegree fromValue(String text) {
    for (KinshipDegree b : KinshipDegree.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<KinshipDegree> {
    @Override
    public void write(final JsonWriter jsonWriter, final KinshipDegree enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public KinshipDegree read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return KinshipDegree.fromValue(String.valueOf(value));
    }
  }
}

