/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 *
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.EmploymentRelationship;
import java.io.IOException;

/**
 * PaymentRelationship
 */




public class PaymentRelationship {
  @SerializedName("employmentRelationship")
  private EmploymentRelationship employmentRelationship = null;

  @SerializedName("homeOffice")
  private Boolean homeOffice = null;

  @SerializedName("id")
  private String id = null;

  public PaymentRelationship employmentRelationship(EmploymentRelationship employmentRelationship) {
    this.employmentRelationship = employmentRelationship;
    return this;
  }

   /**
   * Get employmentRelationship
   * @return employmentRelationship
  **/
  @ApiModelProperty(value = "")
  public EmploymentRelationship getEmploymentRelationship() {
    return employmentRelationship;
  }

  public void setEmploymentRelationship(EmploymentRelationship employmentRelationship) {
    this.employmentRelationship = employmentRelationship;
  }

  public PaymentRelationship homeOffice(Boolean homeOffice) {
    this.homeOffice = homeOffice;
    return this;
  }

   /**
   * Indicar se o vínculo refere-se a um regime de teletrabalho
   * @return homeOffice
  **/
  @ApiModelProperty(value = "Indicar se o vínculo refere-se a um regime de teletrabalho")
  public Boolean isHomeOffice() {
    return homeOffice;
  }

  public void setHomeOffice(Boolean homeOffice) {
    this.homeOffice = homeOffice;
  }

  public PaymentRelationship id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id dos pagamentos
   * @return id
  **/
  @ApiModelProperty(value = "Id dos pagamentos")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRelationship paymentRelationship = (PaymentRelationship) o;
    return Objects.equals(this.employmentRelationship, paymentRelationship.employmentRelationship) &&
        Objects.equals(this.homeOffice, paymentRelationship.homeOffice) &&
        Objects.equals(this.id, paymentRelationship.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employmentRelationship, homeOffice, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRelationship {\n");
    
    sb.append("    employmentRelationship: ").append(toIndentedString(employmentRelationship)).append("\n");
    sb.append("    homeOffice: ").append(toIndentedString(homeOffice)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

