/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.Phonecontact;
import java.io.IOException;

/**
 * Personphonecontact
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-14T17:15:20.586Z")



public class Personphonecontact {
  @SerializedName("person")
  private String person = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("phonecontact")
  private Phonecontact phonecontact = null;

  public Personphonecontact person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Relacionamento com pessoa
   * @return person
  **/
  @ApiModelProperty(value = "Relacionamento com pessoa")
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public Personphonecontact id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id do vínculo
   * @return id
  **/
  @ApiModelProperty(value = "Id do vínculo")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Personphonecontact phonecontact(Phonecontact phonecontact) {
    this.phonecontact = phonecontact;
    return this;
  }

   /**
   * Get phonecontact
   * @return phonecontact
  **/
  @ApiModelProperty(value = "")
  public Phonecontact getPhonecontact() {
    return phonecontact;
  }

  public void setPhonecontact(Phonecontact phonecontact) {
    this.phonecontact = phonecontact;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Personphonecontact personphonecontact = (Personphonecontact) o;
    return Objects.equals(this.person, personphonecontact.person) &&
        Objects.equals(this.id, personphonecontact.id) &&
        Objects.equals(this.phonecontact, personphonecontact.phonecontact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, id, phonecontact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Personphonecontact {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    phonecontact: ").append(toIndentedString(phonecontact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

