/*
 * Folha de Pagamento
 * HCM - Folha de pagamento
 *
 * OpenAPI spec version: 9.0.3
 * Contact: seniorx-dev@senior.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.senior.hcm.payroll.pojos;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import br.com.senior.hcm.payroll.pojos.HolidayType;
import br.com.senior.hcm.payroll.pojos.WorkshiftScale;
import br.com.senior.hcm.payroll.pojos.WorkshiftType;
import java.io.IOException;

/**
 * Workshift
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-14T17:15:20.586Z")



public class Workshift {
  @SerializedName("dsrminutes")
  private Double dsrminutes = null;

  @SerializedName("code")
  private Integer code = null;

  @SerializedName("holidayType")
  private HolidayType holidayType = null;

  @SerializedName("weekminutes")
  private Double weekminutes = null;

  @SerializedName("workshiftScale")
  private WorkshiftScale workshiftScale = null;

  @SerializedName("shift")
  private Integer shift = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("workshiftType")
  private WorkshiftType workshiftType = null;

  @SerializedName("monthminutes")
  private Double monthminutes = null;

  @SerializedName("structure")
  private String structure = null;

  public Workshift dsrminutes(Double dsrminutes) {
    this.dsrminutes = dsrminutes;
    return this;
  }

   /**
   * horas DSR
   * @return dsrminutes
  **/
  @ApiModelProperty(value = "horas DSR")
  public Double getDsrminutes() {
    return dsrminutes;
  }

  public void setDsrminutes(Double dsrminutes) {
    this.dsrminutes = dsrminutes;
  }

  public Workshift code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * Código da escala
   * @return code
  **/
  @ApiModelProperty(value = "Código da escala")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public Workshift holidayType(HolidayType holidayType) {
    this.holidayType = holidayType;
    return this;
  }

   /**
   * Get holidayType
   * @return holidayType
  **/
  @ApiModelProperty(value = "")
  public HolidayType getHolidayType() {
    return holidayType;
  }

  public void setHolidayType(HolidayType holidayType) {
    this.holidayType = holidayType;
  }

  public Workshift weekminutes(Double weekminutes) {
    this.weekminutes = weekminutes;
    return this;
  }

   /**
   * horas semanais
   * @return weekminutes
  **/
  @ApiModelProperty(value = "horas semanais")
  public Double getWeekminutes() {
    return weekminutes;
  }

  public void setWeekminutes(Double weekminutes) {
    this.weekminutes = weekminutes;
  }

  public Workshift workshiftScale(WorkshiftScale workshiftScale) {
    this.workshiftScale = workshiftScale;
    return this;
  }

   /**
   * Get workshiftScale
   * @return workshiftScale
  **/
  @ApiModelProperty(value = "")
  public WorkshiftScale getWorkshiftScale() {
    return workshiftScale;
  }

  public void setWorkshiftScale(WorkshiftScale workshiftScale) {
    this.workshiftScale = workshiftScale;
  }

  public Workshift shift(Integer shift) {
    this.shift = shift;
    return this;
  }

   /**
   * Turno
   * @return shift
  **/
  @ApiModelProperty(value = "Turno")
  public Integer getShift() {
    return shift;
  }

  public void setShift(Integer shift) {
    this.shift = shift;
  }

  public Workshift description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Descrição da escala
   * @return description
  **/
  @ApiModelProperty(value = "Descrição da escala")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Workshift id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id da escala
   * @return id
  **/
  @ApiModelProperty(value = "Id da escala")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Workshift workshiftType(WorkshiftType workshiftType) {
    this.workshiftType = workshiftType;
    return this;
  }

   /**
   * Get workshiftType
   * @return workshiftType
  **/
  @ApiModelProperty(value = "")
  public WorkshiftType getWorkshiftType() {
    return workshiftType;
  }

  public void setWorkshiftType(WorkshiftType workshiftType) {
    this.workshiftType = workshiftType;
  }

  public Workshift monthminutes(Double monthminutes) {
    this.monthminutes = monthminutes;
    return this;
  }

   /**
   * horas mensais
   * @return monthminutes
  **/
  @ApiModelProperty(value = "horas mensais")
  public Double getMonthminutes() {
    return monthminutes;
  }

  public void setMonthminutes(Double monthminutes) {
    this.monthminutes = monthminutes;
  }

  public Workshift structure(String structure) {
    this.structure = structure;
    return this;
  }

   /**
   * Estrutura
   * @return structure
  **/
  @ApiModelProperty(value = "Estrutura")
  public String getStructure() {
    return structure;
  }

  public void setStructure(String structure) {
    this.structure = structure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Workshift workshift = (Workshift) o;
    return Objects.equals(this.dsrminutes, workshift.dsrminutes) &&
        Objects.equals(this.code, workshift.code) &&
        Objects.equals(this.holidayType, workshift.holidayType) &&
        Objects.equals(this.weekminutes, workshift.weekminutes) &&
        Objects.equals(this.workshiftScale, workshift.workshiftScale) &&
        Objects.equals(this.shift, workshift.shift) &&
        Objects.equals(this.description, workshift.description) &&
        Objects.equals(this.id, workshift.id) &&
        Objects.equals(this.workshiftType, workshift.workshiftType) &&
        Objects.equals(this.monthminutes, workshift.monthminutes) &&
        Objects.equals(this.structure, workshift.structure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dsrminutes, code, holidayType, weekminutes, workshiftScale, shift, description, id, workshiftType, monthminutes, structure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Workshift {\n");
    
    sb.append("    dsrminutes: ").append(toIndentedString(dsrminutes)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    holidayType: ").append(toIndentedString(holidayType)).append("\n");
    sb.append("    weekminutes: ").append(toIndentedString(weekminutes)).append("\n");
    sb.append("    workshiftScale: ").append(toIndentedString(workshiftScale)).append("\n");
    sb.append("    shift: ").append(toIndentedString(shift)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    workshiftType: ").append(toIndentedString(workshiftType)).append("\n");
    sb.append("    monthminutes: ").append(toIndentedString(monthminutes)).append("\n");
    sb.append("    structure: ").append(toIndentedString(structure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

